"""Generate a Win64 entry shim for one lifted Daedalus leaf function.

The generated shim contains no program-specific logic. It preserves the exact
target-function entry state, calls the shared MASM bridge, and embeds a pointer
to a ``DaedalusX64Descriptor`` immediately after a two-byte short jump. The
common bridge reads that descriptor without consuming any target GPR.
"""

from __future__ import annotations

import re


_SYMBOL = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

# Fixed encodings emitted by MASM for the template below. The planning layer
# uses these offsets before any output PE exists. Native thunk tests compile the
# same template in both rolling modes.
THUNK_CODE_SIZE = 40
THUNK_COMMON_REL32_OFFSET = 6
THUNK_DESCRIPTOR_POINTER_OFFSET = 12
THUNK_PROLOG_SIZE = 5
THUNK_UNWIND_INFO = bytes.fromhex("0105020005320102")
THUNK_TEMPLATE = bytes.fromhex(
    "9c"                    # pushfq
    "4883ec20"              # sub rsp, 32
    "e800000000"            # call rel32 (hole at +6)
    "eb08"                  # jump over descriptor pointer
    "0000000000000000"      # descriptor VA (hole at +12)
    "833c2400"              # cmp dword ptr [rsp], 0
    "7507"                  # jne failure epilogue
    "4883c428c39090"        # success: add rsp,40; ret; fixed padding
    "b907000000cd29"        # failure: FAST_FAIL_FATAL_APP_EXIT
)

if len(THUNK_TEMPLATE) != THUNK_CODE_SIZE:  # import-time ABI guard
    raise RuntimeError("Win64 thunk template size drift")


def _symbol(value: str, label: str) -> str:
    if not _SYMBOL.fullmatch(value):
        raise ValueError(f"invalid MASM {label}: {value!r}")
    return value


def render_entry_thunk(function_symbol: str, descriptor_symbol: str) -> str:
    """Return MASM source for a CET-balanced, unwindable function-entry shim.

    The descriptor must remain within image relocation reach as a normal qword
    ``OFFSET`` relocation. VM-produced RFLAGS remain available in the VM frame
    for lifted semantics, but Win64 makes physical return flags volatile and the
    legal epilogue does not attempt to export them. A VM/runtime failure is a
    fail-fast termination, never a silent return of the original RAX.
    """
    function_symbol = _symbol(function_symbol, "function symbol")
    descriptor_symbol = _symbol(descriptor_symbol, "descriptor symbol")
    resume = f"{function_symbol}_resume"
    failed = f"{function_symbol}_failed"

    return f"""; Generated by lifter/win64_thunk.py -- do not hand-edit.
OPTION CASEMAP:NONE
EXTERN daedalus_x64_enter_common:PROC
EXTERN {descriptor_symbol}:BYTE
PUBLIC {function_symbol}

.code

{function_symbol} PROC FRAME
    pushfq
    .allocstack 8
    sub     rsp, 32
    .allocstack 32
    .endprolog

    call    daedalus_x64_enter_common
    jmp     SHORT {resume}
    dq      OFFSET {descriptor_symbol}

{resume}:
    cmp     DWORD PTR [rsp], 0
    jne     {failed}
    add     rsp, 40
    ret
    nop
    nop

{failed}:
    mov     ecx, 7              ; FAST_FAIL_FATAL_APP_EXIT
    int     29h
{function_symbol} ENDP

END
"""


def render_entry_thunk_bytes() -> bytes:
    """Return the fixed machine template with REL32/DIR64 fields zeroed."""
    return THUNK_TEMPLATE


__all__ = [
    "THUNK_CODE_SIZE",
    "THUNK_COMMON_REL32_OFFSET",
    "THUNK_DESCRIPTOR_POINTER_OFFSET",
    "THUNK_PROLOG_SIZE",
    "THUNK_TEMPLATE",
    "THUNK_UNWIND_INFO",
    "render_entry_thunk",
    "render_entry_thunk_bytes",
]
