"""
venice_opcodes_shuffled.py
Auto-generated by shuffle_opcodes.py -- DO NOT EDIT
Build seed: a8088df29c2372fba7637e9d737e308b4d4c667752d7e986da66d51581dad14d
"""

# Shuffled opcode table: mnemonic -> (wire_byte, operand_width, operand_kind)
# Drop-in replacement for venice_asm.OPCODES with per-build wire bytes.
SHUFFLED_OPCODES = {
    'halt'          : (0xA3, 0, 'none'),
    'nop'           : (0x9F, 0, 'none'),
    'push_imm8'     : (0x68, 1, 'imm'),
    'push_imm32'    : (0x5D, 4, 'imm'),
    'push_imm64'    : (0xB9, 8, 'imm'),
    'pop'           : (0xD1, 0, 'none'),
    'dup'           : (0xC9, 0, 'none'),
    'swap'          : (0x88, 0, 'none'),
    'add'           : (0xC4, 0, 'none'),
    'sub'           : (0xB8, 0, 'none'),
    'xor'           : (0x52, 0, 'none'),
    'and'           : (0xF2, 0, 'none'),
    'or'            : (0x00, 0, 'none'),
    'shl'           : (0x11, 0, 'none'),
    'shr'           : (0x77, 0, 'none'),
    'mul'           : (0xED, 0, 'none'),
    'load8'         : (0x43, 0, 'none'),
    'load32'        : (0x66, 0, 'none'),
    'load64'        : (0xFA, 0, 'none'),
    'store8'        : (0x24, 0, 'none'),
    'store32'       : (0x17, 0, 'none'),
    'store64'       : (0x06, 0, 'none'),
    'cmp_eq'        : (0xDA, 0, 'none'),
    'cmp_lt'        : (0xC8, 0, 'none'),
    'jmp'           : (0xEA, 4, 'label'),
    'jz'            : (0xE0, 4, 'label'),
    'jnz'           : (0x16, 4, 'label'),
    'call'          : (0xF1, 4, 'label'),
    'push_arg'      : (0x1F, 1, 'imm'),
    'local_addr'    : (0x41, 2, 'imm'),
    'data_addr'     : (0x74, 2, 'imm'),
    'ret'           : (0xC0, 0, 'none'),
    'n_sha256'      : (0x13, 0, 'none'),
    'n_hkdf'        : (0xDB, 0, 'none'),
    'n_xor_buf'     : (0xA5, 0, 'none'),
    'n_getenv'      : (0x8B, 0, 'none'),
    'n_setenv_null' : (0xF3, 0, 'none'),
    'n_hex_decode'  : (0x7B, 0, 'none'),
    'n_zero_mem'    : (0x6F, 0, 'none'),
    'n_scatter_init': (0xC3, 0, 'none'),
    'n_copy_mem'    : (0xA8, 0, 'none'),
    'n_xor_repeat'  : (0x0E, 0, 'none'),
    'n_xor_const'   : (0x12, 0, 'none'),
    'n_call_ptr'    : (0x99, 0, 'none'),
    'div'           : (0xCE, 0, 'none'),
    'mod'           : (0xCF, 0, 'none'),
    'neg'           : (0x37, 0, 'none'),
    'not'           : (0xCC, 0, 'none'),
    'cmp_gt'        : (0x9D, 0, 'none'),
    'cmp_ge'        : (0x33, 0, 'none'),
    'cmp_ne'        : (0x90, 0, 'none'),
    'push_imm16'    : (0x76, 2, 'imm'),
    'load16'        : (0xD7, 0, 'none'),
    'store16'       : (0x02, 0, 'none'),
    'rot3'          : (0xB3, 0, 'none'),
    'pick'          : (0x97, 1, 'imm'),
}

# Decoy wire bytes (single-byte no-op instructions for noise insertion)
DECOY_WIRE_BYTES = [0x72, 0xFC, 0xF8, 0xB5, 0xDE, 0x5C, 0x83, 0xD0, 0x9A, 0x3A, 0x5A, 0x7A, 0x3B, 0x19, 0xC2, 0x78, 0x1D]

# Fraction of real instructions to pad with randomly-inserted decoy bytes
NOISE_RATIO = 0.15

# Reproducible build seed (hex)
BUILD_SEED = 'a8088df29c2372fba7637e9d737e308b4d4c667752d7e986da66d51581dad14d'

